# Generated by Django 4.2.1 on 2023-05-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_movie_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie_code',
        ),
    ]
